// src/components/button/index.tsx
import type { ComponentProps } from 'react'
import { clsx } from 'kotl'
import { createVariantClass } from '../internal-style'

type ButtonProps = Omit<ComponentProps<'button'>, 'disabled'> & {
  variant?: 'solid' | 'soft' | 'outline' | 'text' | 'pure' | 'default'
  color?: 'primary' | 'success' | 'warning' | 'danger'
  size?: 'sm' | 'md' | 'lg'
  pill?: boolean
  square?: boolean
  block?: boolean
  loading?: boolean
  disabled?: boolean
}

// Dependencies: pnpm install lucide-react

function style(props: Pick<ButtonProps, 'variant' | 'color' | 'size' | 'pill' | 'square' | 'block'>) {
  const { variant = 'default', color, size, pill, square, block } = props

  return clsx([
    `inline-flex items-center justify-center whitespace-nowrap text-sm font-medium transition-colors cursor-pointer 
    outline-offset-2 focus-visible:outline-2 focus-visible:outline-primary-500/70 
    disabled:pointer-events-none disabled:opacity-50
    [&_svg]:pointer-events-none
    [&_svg]:shrink-0 
    shadow-sm shadow-black/5 h-9 px-4 py-2`,
    pill ? 'rounded-full' : 'rounded-md',
    block && 'block',
    createVariantClass(variant, ''),
  ])
}

export function Button(props: ButtonProps) {
  const {
    variant,
    color,
    size,
    pill,
    square,
    block,
    loading,
    disabled,
    className: _className,
    children,
    ...rest
  } = props
  const fullClassName = style(props)
  return (
    <button {...rest} className={fullClassName} disabled={disabled}>
      {children}
    </button>
  )
}

// src/components/Button.vue
<script setup lang="ts">
import type { ClassValue } from 'kotl'

import { LoaderCircleIcon } from 'lucide-vue-next'
import { computed } from 'vue'
import { cn } from '../lib/utils'

export type ButtonProps = {
  variant?: 'default' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link'
  size?: 'default' | 'sm' | 'lg'
  pill?: boolean
  square?: boolean
  disabled?: boolean
  loading?: boolean
}

const emit = defineEmits<{ click: [event: MouseEvent] }>()
const slots = defineSlots<{ default?(_: {}): any }>()
const props = withDefaults(defineProps<ButtonProps & { class?: ClassValue }>(), {
  variant: 'default',
  size: 'default',
})

const rootClass = computed(() => {
  return cn(
    "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:ring-focus aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
    {
      default: 'bg-primary text-primary-foreground shadow-xs hover:bg-primary/90',
      destructive:
        'bg-destructive text-white shadow-xs hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60',
      outline:
        'border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50',
      secondary: 'bg-secondary text-secondary-foreground shadow-xs hover:bg-secondary/80',
      ghost: 'hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50',
      link: 'text-primary underline-offset-4 hover:underline',
    }[props.variant],
    {
      default: props.square ? 'size-9' : 'h-9 px-4 py-2 has-[>svg]:px-3',
      sm: props.square ? 'size-8' : 'h-8 gap-1.5 px-3 has-[>svg]:px-2.5',
      lg: props.square ? 'size-10' : 'h-10 px-6 has-[>svg]:px-4',
    }[props.size],
    props.pill && 'rounded-full',
    props.class
  )
})
</script>
<template>
  <button type="button" :class="rootClass" :disabled="disabled" @click="emit('click', $event)">
    <LoaderCircleIcon v-if="loading" class="animate-spin" />
    <slot />
  </button>
</template>
